version: '3'

services:

  web:
     container_name: web
     networks:
      - employee-mysql
     depends_on:
       - db
     links:
       - db
     build:     
       dockerfile: Dockerfile      
     ports:
       - '8080:8080' 
     environment:      
      MYSQL_ROOT_PASSWORD: jsfprimefaces
      MYSQL_DATABASE: jsfprimefaces
      DATABASE_HOST: db
     
  db:
    image: mysql:5.7
    container_name: db    
    environment:
      MYSQL_ROOT_PASSWORD: jsfprimefaces
      MYSQL_DATABASE: cursojsfprimefaces     
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql 

    networks:
      - employee-mysql   

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80 

    networks:
      - employee-mysql
 
       
volumes:
  dbdata:

networks:
  employee-mysql: 
